// Centralized Arabic labels — see CLAUDE.md conventions. Components read
// display strings from here, never inline, so wording changes don't require
// touching component logic.
import type { AppRole, ContactType, PaymentMethod, PoStatus, SoStatus, StockSource, UnitType } from '@/types/database';

export const APP_NAME = 'مخزون شبانه';
export const ORG_NAME = 'شبانة لتجارة الألوميتال';

export const NAV = {
  dashboard: 'لوحة التحكم',
  purchases: 'أوامر الشراء',
  inventory: 'المخزون',
  sales: 'أوامر البيع',
  contacts: 'جهات الاتصال',
  reports: 'التقارير',
  audit: 'سجل النشاط',
  users: 'المستخدمون',
  settings: 'الإعدادات',
  more: 'المزيد',
  comingSoon: 'قريبًا',
  mainSection: 'القوائم الرئيسية',
  otherSection: 'أخرى',
} as const;

export const AUTH = {
  loginTitle: 'تسجيل الدخول',
  // Shown only until the business is known (or when it can't be: the generic
  // /login door). It must NOT name a specific business — every client sees it.
  loginSubtitle: 'إدارة المخزون والمبيعات',
  // PC edition: the local API is not answering. Shown instead of letting the
  // owner type credentials into a form that cannot possibly succeed.
  serviceUnreachable: 'تعذّر الاتصال بخدمة البرنامج على هذا الجهاز. انتظر لحظة ثم أعد تحميل الصفحة، أو أعد تشغيل الجهاز.',
  email: 'البريد الإلكتروني',
  username: 'اسم المستخدم',
  usernamePlaceholder: 'اسم المستخدم',
  orgCode: 'كود المنشأة',
  orgCodePlaceholder: 'مثال: shabana',
  orgCodeHint: 'الكود الموجود في رابط الدخول الخاص بمنشأتك',
  invalidOrgCode: 'كود المنشأة غير صحيح',
  password: 'كلمة المرور',
  submit: 'دخول',
  submitting: 'جارٍ الدخول...',
  logout: 'تسجيل الخروج',
  invalidCredentials: 'اسم المستخدم أو كلمة المرور غير صحيحة',
  genericError: 'حدث خطأ، حاول مرة أخرى',
  sessionExpired: 'انتهت الجلسة، يرجى تسجيل الدخول مرة أخرى',
} as const;

// PC EDITION ONLY — first-run setup screen (see services/setup.ts).
export const SETUP = {
  title: 'الإعداد الأول',
  subtitle: 'أهلاً بك. لنجهّز البرنامج لأول مرة على هذا الجهاز.',
  businessName: 'اسم المنشأة',
  businessNamePlaceholder: 'مثال: شبانة لتجارة الألوميتال',
  businessNameHint: 'يظهر في الفواتير وصفحة الدخول.',
  adminFullName: 'اسم المدير',
  adminFullNamePlaceholder: 'الاسم الذي يظهر في البرنامج',
  adminUsername: 'اسم مستخدم المدير',
  adminUsernameHint: 'حروف إنجليزية وأرقام فقط — به تسجّل الدخول.',
  adminPassword: 'كلمة المرور',
  adminPasswordConfirm: 'تأكيد كلمة المرور',
  siteName: 'اسم الفرع الأول',
  siteNamePlaceholder: 'الفرع الرئيسي',
  submit: 'إنشاء وبدء الاستخدام',
  submitting: 'جارٍ الإعداد...',
  passwordTooShort: 'كلمة المرور يجب ألا تقل عن ٦ أحرف.',
  passwordMismatch: 'كلمتا المرور غير متطابقتين.',
  invalidUsername: 'اسم المستخدم يجب أن يكون حروفاً إنجليزية وأرقاماً فقط.',
  alreadySetup: 'تم إعداد هذا الجهاز بالفعل.',
  invalidInput: 'تحقق من البيانات المدخلة.',
  genericError: 'تعذّر إكمال الإعداد. حاول مرة أخرى.',
} as const;

// PC EDITION ONLY — backup status badge on the Dashboard (see
// components/pc/PcBackupStatus.tsx). Fed by /pc/last-backup.json, which
// backup.ps1 writes after each nightly run.
export const PC_BACKUP = {
  never: 'لم يتم أخذ نسخة احتياطية بعد',
  last: 'آخر نسخة احتياطية',
  today: 'اليوم',
  yesterday: 'أمس',
  daysAgo: (n: number) => `منذ ${n} يوم`,
  failed: 'فشلت آخر نسخة احتياطية — راجع الإعدادات',
  stale: 'لم تُؤخذ نسخة احتياطية منذ أكثر من يومين',
} as const;

export const ROLE_LABEL: Record<AppRole, string> = {
  admin: 'مدير عام',
  manager: 'مدير مخازن',
  staff: 'موظف',
};

export const SITE = {
  allSites: 'كل الفروع',
  switcher: 'الفرع',
} as const;

export const CONTACT_TYPE_LABEL: Record<ContactType, string> = {
  vendor: 'مورد',
  client: 'عميل',
  both: 'عميل ومورد',
};

export const UNIT_LABEL: Record<UnitType, string> = {
  kg: 'كجم',
  unit: 'وحدة',
};

export const PAYMENT_METHOD_LABEL: Record<PaymentMethod, string> = {
  cash: 'كاش',
  instapay: 'انستاباي',
  bank_transfer: 'تحويل بنكي',
  credit: 'رصيد العميل',
};

export const PO_STATUS_LABEL: Record<PoStatus, string> = {
  open: 'مفتوح',
  fully_converted: 'محول بالكامل',
  closed: 'مغلق',
};

export const SO_STATUS_LABEL: Record<SoStatus, string> = {
  draft: 'مسودة',
  invoiced: 'مفوترة',
  placed: 'منفذة',
  closed: 'مغلقة',
};

export const COMMON = {
  loading: 'جارٍ التحميل...',
  save: 'حفظ',
  cancel: 'إلغاء',
  delete: 'حذف',
  edit: 'تعديل',
  add: 'إضافة',
  confirm: 'تأكيد',
  search: 'بحث',
  noData: 'لا توجد بيانات',
  currency: 'ج.م',
  offlineBanner: 'أنت غير متصل بالإنترنت',
} as const;

/** Shared table chrome: the per-column filter popovers and the sort toggles. */
export const TABLE = {
  filterAria: 'تصفية العمود',
  sortAria: 'ترتيب حسب العمود',
  filterSearch: 'ابحث في الخيارات...',
  selectAll: 'تحديد الكل',
  clearColumn: 'مسح',
  done: 'تم',
  clearAll: 'مسح كل الفلاتر',
  noOptions: 'لا توجد خيارات',
  noMatch: 'لا توجد نتائج مطابقة للفلاتر',
  showingCount: (shown: number, total: number) =>
    `عرض ${shown.toLocaleString('ar-EG')} من ${total.toLocaleString('ar-EG')}`,
} as const;

/** Global search overlay (⌘/Ctrl + K, or the magnifier in the header). */
export const SEARCH = {
  open: 'بحث',
  placeholder: 'ابحث في كل شيء...',
  hint: 'اكتب للبحث في أوامر الشراء والبيع والأصناف وجهات الاتصال',
  noResults: 'لا توجد نتائج',
  close: 'إغلاق',
  groupPurchases: 'أوامر الشراء',
  groupSales: 'أوامر البيع',
  groupItems: 'الأصناف',
  groupContacts: 'جهات الاتصال',
  moreSuffix: (n: number) => `و${n.toLocaleString('ar-EG')} نتيجة أخرى`,
  navHint: '↑↓ للتنقل · Enter للفتح · Esc للإغلاق',
} as const;

/** المرفقات — the vendor's paper order scanned or photographed onto the PO. */
export const ATTACHMENTS = {
  title: 'المرفقات',
  subtitle: 'صور أو ملفات أمر الشراء الورقي من المورد',
  camera: 'تصوير',
  pickFile: 'إرفاق ملف',
  uploading: 'جارٍ الرفع...',
  none: 'لا توجد مرفقات',
  open: 'فتح',
  download: 'تنزيل',
  delete: 'حذف المرفق',
  deleteConfirm: 'سيتم حذف هذا المرفق نهائيًا. هل تريد المتابعة؟',
  deleted: 'تم حذف المرفق',
  uploaded: 'تمت إضافة المرفق',
  tooLarge: 'حجم الملف أكبر من ١٠ ميجابايت',
  badType: 'نوع الملف غير مدعوم — استخدم صورة أو PDF',
  uploadError: 'تعذر رفع الملف، حاول مرة أخرى',
  pdfBadge: 'ملف PDF',
  close: 'إغلاق',
} as const;

export const ERROR_BOUNDARY = {
  title: 'حدث خطأ غير متوقع',
  message: 'واجه التطبيق مشكلة أثناء عرض هذه الصفحة. حاول إعادة التحميل، وإذا استمرت المشكلة تواصل مع الدعم الفني.',
  reload: 'إعادة تحميل الصفحة',
  backToDashboard: 'العودة إلى لوحة التحكم',
} as const;

export const ORG_INFO = {
  addressLine: 'دمياط الجديدة، طريق دمياط الجديدة – كفر البطيخ',
  phoneLine: 'هاتف: 057-2401180',
} as const;

export const CONTACTS = {
  title: 'جهات الاتصال',
  subtitle: 'العملاء والموردون وأرصدتهم الحالية',
  searchPlaceholder: 'ابحث بالاسم أو الهاتف...',
  allTypes: 'الكل',
  addContact: 'إضافة جهة اتصال',
  editContact: 'تعديل بيانات جهة الاتصال',
  colName: 'الاسم',
  colPhone: 'الهاتف',
  colBalance: 'الرصيد',
  noContacts: 'لا توجد جهات اتصال بعد',
  backToList: 'جهات الاتصال',
  phones: 'أرقام الهاتف',
  paymentMethods: 'طرق الدفع',
  printStatement: 'طباعة كشف حساب',
  transactions: 'الحركات',
  noTransactions: 'لا توجد حركات مسجلة على هذا الحساب بعد',
  colDate: 'التاريخ',
  colDesc: 'البيان',
  colDebit: 'مدين',
  colCredit: 'دائن',
} as const;

export const CONTACT_BALANCE = {
  receivableTag: 'عليه',
  payableTag: 'له',
  settledTag: 'متسوي',
  receivableSub: 'مستحق من الطرف',
  payableSub: 'مستحق للطرف',
  settledSub: 'لا يوجد رصيد مستحق',
} as const;

export const CONTACT_FORM = {
  name: 'الاسم',
  namePlaceholder: 'اسم جهة الاتصال',
  type: 'النوع',
  primaryPhone: 'رقم الهاتف الأساسي',
  extraPhones: 'أرقام إضافية',
  addPhone: 'إضافة رقم',
  removePhone: 'حذف الرقم',
  address: 'العنوان',
  notes: 'ملاحظات',
  paymentMethod: 'طريقة الدفع',
  instapayNumber: 'رقم انستاباي',
  bankName: 'اسم البنك',
  accountNumber: 'رقم الحساب',
  addPaymentMethod: 'إضافة طريقة دفع',
  removePaymentMethod: 'حذف الطريقة',
  nameRequired: 'الاسم مطلوب',
  primaryPhoneRequired: 'رقم الهاتف الأساسي مطلوب',
  invalidPhone: 'رقم هاتف مصري غير صحيح — موبايل (01012345678) أو أرضي (0572401180)',
  instapayNumberRequired: 'رقم انستاباي مطلوب',
  bankDetailsRequired: 'اسم البنك ورقم الحساب مطلوبان',
  saveError: 'تعذر حفظ جهة الاتصال، حاول مرة أخرى',
  savedNew: 'تمت إضافة جهة الاتصال',
  savedEdit: 'تم حفظ التعديلات',
} as const;

export const STATEMENT = {
  title: 'كشف حساب',
  back: 'عودة',
  print: 'طباعة',
  issueDate: 'تاريخ الإصدار',
  period: 'الفترة',
  accountName: 'اسم الحساب',
  accountType: 'النوع',
  finalBalance: 'الرصيد النهائي',
  from: 'من',
  to: 'إلى',
  clientSignature: 'توقيع العميل / المورد',
  accountantSignature: 'توقيع المحاسب',
  noRows: 'لا توجد حركات في هذه الفترة',
} as const;

export const STOCK_SOURCE_LABEL: Record<StockSource, string> = {
  po_conversion: 'تحويل من أمر شراء',
  sale: 'بيع',
  adjustment: 'تسوية',
  transfer: 'نقل',
  opening: 'رصيد افتتاحي',
};

export const INVENTORY = {
  title: 'المخزون',
  subtitle: 'أرصدة الأصناف في كل الفروع',
  addItem: 'إضافة صنف',
  editItem: 'تعديل بيانات الصنف',
  transferBetweenSites: 'نقل بين الفروع',
  colItem: 'الصنف',
  colSite: 'الفرع',
  colQty: 'الكمية',
  colMin: 'الحد الأدنى',
  colStatus: 'الحالة',
  colSalePrice: 'سعر البيع',
  statusLow: 'منخفض',
  statusOk: 'متوفر',
  noItems: 'لا توجد أصناف بعد',
  backToList: 'المخزون',
  perSiteStock: 'الرصيد حسب الفرع',
  movementHistory: 'حركات المخزون',
  noMovements: 'لا توجد حركات مسجلة على هذا الصنف بعد',
  colDate: 'التاريخ',
  colType: 'النوع',
  colChange: 'التغير',
  colNote: 'ملاحظة',
  adjust: 'تسوية',
  unitType: 'وحدة القياس',
  lowStockThreshold: 'الحد الأدنى للتنبيه',
  salePrice: 'سعر البيع',
  itemName: 'اسم الصنف',
  itemNamePlaceholder: 'اسم الصنف',
  active: 'نشط',
  nameRequired: 'اسم الصنف مطلوب',
  saveError: 'تعذر حفظ الصنف، حاول مرة أخرى',
  savedNew: 'تمت إضافة الصنف',
  savedEdit: 'تم حفظ التعديلات',
} as const;

export const TRANSFER = {
  title: 'نقل بين الفروع',
  submit: 'تنفيذ النقل',
  item: 'الصنف',
  fromSite: 'من فرع',
  toSite: 'إلى فرع',
  qty: 'الكمية',
  qtyPlaceholder: 'أدخل الكمية',
  note: 'ملاحظة (اختياري)',
  available: 'المتاح',
  sameSiteError: 'اختر فرعين مختلفين',
  qtyRequired: 'أدخل كمية أكبر من صفر',
  insufficientStock: 'الكمية غير كافية في الفرع المصدر',
  success: 'تم تنفيذ النقل بنجاح',
  genericError: 'تعذر تنفيذ النقل، حاول مرة أخرى',
} as const;

export const ADJUSTMENT = {
  title: 'تسوية مخزون',
  site: 'الفرع',
  changeAmount: 'مقدار التغير (+/-)',
  changeHint: 'قيمة موجبة لزيادة الرصيد، وسالبة لخصمه',
  reason: 'سبب التسوية',
  reasonPlaceholder: 'اكتب سبب التسوية...',
  reasonRequired: 'سبب التسوية مطلوب',
  amountRequired: 'أدخل قيمة تغير غير صفرية',
  submit: 'تنفيذ التسوية',
  success: 'تم تسجيل التسوية',
  genericError: 'تعذر تنفيذ التسوية، حاول مرة أخرى',
} as const;

export const OPENING = {
  title: 'الأرصدة الافتتاحية',
  button: 'رصيد افتتاحي',
  intro:
    'اكتب الكمية الموجودة فعليًا لكل صنف في هذا الفرع، والتطبيق يسجّل الفرق تلقائيًا. اترك الخانة فارغة لأي صنف لا تريد تغييره.',
  site: 'الفرع',
  colItem: 'الصنف',
  colCurrent: 'الرصيد الحالي',
  colActual: 'الرصيد الفعلي',
  colDiff: 'الفرق',
  note: 'ملاحظة (اختياري)',
  notePlaceholder: 'مثال: جرد بداية التشغيل ٢٠٢٦',
  noChanges: 'لم تغيّر أي رصيد بعد',
  negative: 'الرصيد الفعلي لا يمكن أن يكون سالبًا',
  submit: 'حفظ الأرصدة',
  confirm: (n: number) => `سيتم تعديل رصيد ${n.toLocaleString('ar-EG')} صنف. متابعة؟`,
  confirmSubmit: 'تأكيد الحفظ',
  success: (n: number) => `تم ضبط رصيد ${n.toLocaleString('ar-EG')} صنف`,
  noItems: 'لا توجد أصناف بعد — أضف الأصناف أولًا',
  genericError: 'تعذر حفظ الأرصدة، حاول مرة أخرى',
} as const;

export const PURCHASES = {
  title: 'أوامر الشراء',
  subtitle: 'متابعة أوامر الشراء وتحويلها إلى المخزون بالفروع',
  addPo: 'إضافة أمر شراء',
  newPo: 'أمر شراء جديد',
  editPo: 'تعديل أمر الشراء',
  edit: 'تعديل',
  editConvertedWarning: 'تم تحويل جزء من هذا الأمر إلى المخزون — لا يمكن جعل إجمالي الكيلوهات أقل من المحوّل بالفعل.',
  colCode: 'رقم الأمر',
  colVendor: 'المورد',
  colProduct: 'المنتج',
  colDate: 'التاريخ',
  colConversion: 'التحويل إلى المخزون',
  colTotal: 'الإجمالي',
  colPayStatus: 'حالة السداد',
  noPos: 'لا توجد أوامر شراء بعد',
  backToList: 'أوامر الشراء',
  detailHeading: 'أمر الشراء',
  orderNoun: 'أمر شراء',
  // detail KPIs
  totalKg: 'الكمية الكلية',
  convertedKg: 'المحول للمخزون',
  total: 'الإجمالي',
  paidRemaining: 'المدفوع / المتبقي',
  remainingSuffix: 'متبقي',
  fullyPaid: 'مدفوع بالكامل',
  // list filter options (grouped values, not stored columns)
  payPartial: 'غير مكتمل السداد',
  convNotStarted: 'لم يبدأ',
  convPartial: 'جزئي',
  convDone: 'مكتمل',
  // conversion panel
  conversionsTitle: 'التحويل إلى المخزون',
  addConversion: 'تحويل إلى المخزون',
  remainingKg: 'المتبقي للتحويل',
  by: 'بواسطة',
  reverseConversion: 'التراجع عن التحويل',
  reverseConfirmTitle: 'التراجع عن التحويل',
  reverseConfirmMsg: 'سيتم خصم الكمية الناتجة من مخزون الفرع. لا يمكن التراجع إذا كان الرصيد غير كافٍ. هل تريد المتابعة؟',
  reversed: 'تم التراجع عن التحويل',
  reverseError: 'تعذر التراجع عن التحويل',
  // itemized order (أمر مصنّف)
  itemizedBadge: 'مصنّف',
  itemsCountSuffix: 'صنف',
  linesTitle: 'أصناف الأمر',
  colSite: 'الفرع',
  colQty: 'الكمية',
  colPrice: 'السعر',
  editItemizedWarning:
    'تعديل الأصناف يُلغي كل عمليات التحويل إلى المخزون المرتبطة بها (ويُرجِع مخزونها)، وستحتاج لإعادة التحويل بعد الحفظ.',
  // itemized line receiving (conversion)
  colOrdered: 'المطلوب',
  colReceived: 'المُستلم',
  colRemaining: 'المتبقي',
  receiveAction: 'تحويل',
  receivedTag: 'مكتمل',
  lineConversionsTitle: 'عمليات الاستلام إلى المخزون',
  reverseLineConv: 'التراجع عن الاستلام',
  reverseLineConvMsg: 'سيتم خصم الكمية من مخزون الفرع. لا يمكن التراجع إذا كان الرصيد غير كافٍ. هل تريد المتابعة؟',
} as const;

export const ITEMIZED_CONVERT = {
  title: 'تحويل صنف إلى المخزون',
  line: 'الصنف',
  site: 'الفرع الوجهة',
  qty: 'الكمية المستلمة',
  remaining: 'المتبقي من البند',
  qtyRequired: 'أدخل كمية أكبر من صفر',
  exceeds: 'الكمية تتجاوز المتبقي من البند',
  success: 'تم التحويل إلى المخزون',
  error: 'تعذر تنفيذ التحويل، حاول مرة أخرى',
} as const;

export const PO_FORM = {
  vendor: 'المورد',
  vendorPlaceholder: 'اختر المورد',
  productName: 'اسم المنتج',
  productNamePlaceholder: 'مثال: ألومنيوم خام',
  notes: 'ملاحظات',
  notesPlaceholder: 'ملاحظات إضافية (اختياري)',
  orderDate: 'تاريخ الأمر',
  totalKg: 'إجمالي الكيلوهات',
  pricePerKg: 'سعر الكيلو',
  total: 'الإجمالي',
  computed: 'محسوب تلقائيًا',
  vendorRequired: 'يجب اختيار المورد',
  kgRequired: 'أدخل إجمالي كيلوهات أكبر من صفر',
  amountsRequired: 'أكمل حقلين على الأقل من حقول التسعير',
  saveError: 'تعذر حفظ أمر الشراء، حاول مرة أخرى',
  saved: 'تم إنشاء أمر الشراء',
  savedEdit: 'تم حفظ التعديلات',
  // itemized order (أمر مصنّف)
  poType: 'نوع الأمر',
  typeGeneral: 'أمر عام (بالوزن)',
  typeItemized: 'أمر مصنّف (أصناف)',
  lines: 'الأصناف',
  item: 'الصنف',
  itemPlaceholder: 'اختر صنفًا',
  newItemOption: '＋ صنف جديد',
  newItemName: 'اسم الصنف الجديد',
  newItemNamePlaceholder: 'اكتب اسم الصنف',
  newItemUnit: 'الوحدة',
  qty: 'الكمية',
  itemUnitPrice: 'سعر الوحدة',
  destSite: 'الفرع',
  lineTotal: 'الإجمالي',
  addLine: 'إضافة صنف',
  addLine5: 'إضافة 5 أصناف',
  addLine10: 'إضافة 10 أصناف',
  removeLine: 'حذف الصنف',
  grandTotal: 'إجمالي الأمر',
  linesRequired: 'أضف صنفًا واحدًا على الأقل',
  lineInvalid: 'أكمل بيانات كل صنف (الصنف، الكمية، السعر، الفرع)',
  newNameRequired: 'أدخل اسم الصنف الجديد',
  savedItemized: 'تم إنشاء أمر الشراء المصنّف',
} as const;

export const CONVERSION_FORM = {
  title: 'تحويل إلى المخزون',
  item: 'الصنف',
  site: 'الفرع الوجهة',
  kgConsumed: 'الكمية المستهلكة (كجم)',
  outputQty: 'الكمية الناتجة',
  outputUnit: 'وحدة الناتج',
  available: 'المتبقي للتحويل',
  kgRequired: 'أدخل كمية مستهلكة أكبر من صفر',
  outputRequired: 'أدخل كمية ناتجة أكبر من صفر',
  exceedsRemaining: 'الكمية المستهلكة تتجاوز المتبقي من أمر الشراء',
  success: 'تم التحويل إلى المخزون',
  genericError: 'تعذر تنفيذ التحويل، حاول مرة أخرى',
} as const;

export const DASHBOARD = {
  title: 'لوحة التحكم',
  subtitle: 'أداء الفرع لليوم المحدد — الأرصدة والحركة والتحصيلات',
  date: 'التاريخ',
  // KPI cards
  openingCash: 'رصيد أول اليوم',
  salesToday: 'مبيعات اليوم',
  collectionsToday: 'تحصيلات اليوم',
  closingCash: 'رصيد الخزينة آخر اليوم',
  openingHint: 'خزينة بداية اليوم (= آخر أمس)',
  // sections
  collectionsTitle: 'التحصيلات حسب الطريقة',
  payoutsTitle: 'المدفوعات للموردين حسب الطريقة',
  noCollections: 'لا توجد تحصيلات في هذا اليوم',
  noPayouts: 'لا توجد مدفوعات في هذا اليوم',
  collectionsTotalTag: 'إجمالي التحصيل',
  payoutsTotalTag: 'إجمالي المدفوع',
  lowStockTitle: 'تنبيه انخفاض المخزون',
  lowStockCol: 'الصنف',
  lowStockSite: 'الفرع',
  lowStockQty: 'المتاح',
  lowStockThreshold: 'الحد الأدنى',
  noLowStock: 'لا توجد أصناف منخفضة المخزون',
  topItemsTitle: 'الأصناف الأكثر مبيعًا',
  topItemsAxis: 'الكمية المباعة',
  noTopItems: 'لا توجد مبيعات في هذا اليوم',
  drawersTitle: 'خزائن الفروع آخر اليوم',
  combinedTotal: 'الإجمالي المجمّع',
} as const;

export const SALES = {
  title: 'أوامر البيع',
  subtitle: 'إنشاء أوامر البيع وفوترتها وتنفيذها وتحصيلها',
  addSo: 'إضافة أمر بيع',
  newSo: 'أمر بيع جديد',
  editSo: 'تعديل أمر البيع',
  colCode: 'رقم الأمر',
  colClient: 'العميل',
  colSite: 'الفرع',
  colDate: 'التاريخ',
  colTotal: 'الإجمالي',
  colStatus: 'الحالة',
  colPayStatus: 'حالة السداد',
  noSos: 'لا توجد أوامر بيع بعد',
  draftCode: 'مسودة',
  backToList: 'أوامر البيع',
  detailHeading: 'أمر البيع',
  orderNoun: 'أمر بيع',
  // KPIs
  total: 'الإجمالي',
  subtotal: 'إجمالي البنود',
  discount: 'الخصم',
  afterDiscount: 'بعد الخصم',
  paidRemaining: 'المدفوع / المتبقي',
  remainingSuffix: 'متبقي',
  fullyPaid: 'مدفوع بالكامل',
  payPartial: 'غير مكتمل السداد',
  status: 'الحالة',
  linesCount: 'عدد البنود',
  // lifecycle actions
  invoice: 'فوترة',
  place: 'تنفيذ',
  cancelPlacement: 'إلغاء التنفيذ',
  printInvoice: 'طباعة الفاتورة',
  editDraft: 'تعديل المسودة',
  edit: 'تعديل',
  editLockedWarning: 'هذا الأمر تمت فوترته أو تنفيذه — الحفظ سيعيد احتساب المخزون تلقائيًا (إرجاع الكميات القديمة وخصم الجديدة) للحفاظ على صحة الأرصدة.',
  // lines panel
  linesTitle: 'بنود الأمر',
  colItem: 'الصنف',
  colQty: 'الكمية',
  colUnitPrice: 'سعر الوحدة',
  colLineTotal: 'الإجمالي',
  noLines: 'لا توجد بنود على هذا الأمر',
  by: 'بواسطة',
  // confirms & toasts
  invoiceConfirmTitle: 'فوترة أمر البيع',
  invoiceConfirmMsg: 'سيتم تثبيت البنود وإصدار رقم فاتورة. لا يمكن تعديل البنود بعد الفوترة. هل تريد المتابعة؟',
  placeConfirmTitle: 'تنفيذ أمر البيع',
  placeConfirmMsg: 'سيتم خصم الكميات من مخزون الفرع. هل تريد المتابعة؟',
  cancelConfirmTitle: 'إلغاء تنفيذ الأمر',
  cancelConfirmMsg: 'سيتم إرجاع الكميات إلى مخزون الفرع. هل تريد المتابعة؟',
  invoiced: 'تمت الفوترة',
  placed: 'تم التنفيذ وخصم المخزون',
  cancelled: 'تم إلغاء التنفيذ وإرجاع المخزون',
  invoiceError: 'تعذرت الفوترة',
  placeError: 'تعذر التنفيذ',
  cancelError: 'تعذر إلغاء التنفيذ',
  draftNoPayments: 'لا يمكن تسجيل دفعات على مسودة — قم بالفوترة أولاً',
} as const;

export const SO_FORM = {
  site: 'الفرع',
  client: 'العميل',
  clientPlaceholder: 'اختر العميل',
  orderDate: 'تاريخ الأمر',
  lines: 'البنود',
  item: 'الصنف',
  qty: 'الكمية',
  unitPrice: 'سعر الوحدة',
  unitPriceByKg: 'سعر الكيلو',
  lineTotal: 'الإجمالي',
  addLine: 'إضافة بند',
  removeLine: 'حذف البند',
  grandTotal: 'إجمالي الأمر',
  // discount (migration 0030)
  discount: 'الخصم',
  discountNone: 'بدون',
  discountAmount: 'مبلغ',
  discountPercent: 'نسبة',
  discountAmountPlaceholder: 'قيمة الخصم بالجنيه',
  discountPercentPlaceholder: 'نسبة الخصم ٪',
  subtotal: 'إجمالي البنود',
  discountLine: 'الخصم',
  netTotal: 'الإجمالي بعد الخصم',
  discountTooBig: 'الخصم أكبر من إجمالي البنود',
  discountPercentTooBig: 'نسبة الخصم لا يمكن أن تتجاوز ١٠٠٪',
  discountRequired: 'أدخل قيمة الخصم أو اختر «بدون»',
  // Stock shown per line while writing the order (against the SO's own فرع).
  available: 'المتاح',
  stockLoading: 'جارٍ قراءة الرصيد…',
  notEnoughStock: 'الكمية أكبر من المتاح',
  clientRequired: 'يجب اختيار العميل',
  siteRequired: 'يجب اختيار الفرع',
  linesRequired: 'أضف بندًا واحدًا على الأقل',
  lineInvalid: 'أكمل بيانات كل بند (الصنف والكمية والسعر)',
  saveError: 'تعذر حفظ أمر البيع، حاول مرة أخرى',
  savedNew: 'تم إنشاء مسودة أمر البيع',
  savedEdit: 'تم حفظ التعديلات',
} as const;

export const INVOICE = {
  title: 'فاتورة بيع',
  back: 'عودة',
  print: 'طباعة',
  invoiceNumber: 'رقم الفاتورة',
  issueDate: 'تاريخ الإصدار',
  orderDate: 'تاريخ الأمر',
  client: 'العميل',
  site: 'الفرع',
  colIndex: 'م',
  colItem: 'الصنف',
  colQty: 'الكمية',
  colUnitPrice: 'سعر الوحدة',
  colLineTotal: 'الإجمالي',
  subtotal: 'إجمالي البنود',
  discount: 'الخصم',
  grandTotal: 'الإجمالي الكلي',
  paid: 'المدفوع',
  remaining: 'المتبقي',
  clientSignature: 'توقيع العميل',
  sellerSignature: 'توقيع البائع',
  notInvoiced: 'لم تتم فوترة هذا الأمر بعد',
} as const;

export const PAYMENTS = {
  title: 'سجل الدفعات',
  paid: 'مدفوع',
  remaining: 'متبقي',
  addPayment: 'إضافة دفعة',
  amount: 'المبلغ',
  method: 'الطريقة',
  date: 'التاريخ',
  note: 'ملاحظة',
  drawerSite: 'من خزينة أي فرع؟',
  instapayAccount: 'رقم الانستاباي',
  bankAccount: 'الحساب البنكي',
  selectAccount: 'اختر الحساب',
  noAccountForMethod: 'لا يوجد حساب محفوظ بهذه الطريقة لجهة الاتصال — أضِفه من صفحة جهة الاتصال أولاً',
  noPayments: 'لا توجد دفعات مسجلة بعد',
  amountRequired: 'أدخل مبلغًا أكبر من صفر',
  cashSiteRequired: 'يجب تحديد فرع الخزينة للدفعة النقدية',
  overpay: 'المبلغ يتجاوز المتبقي على الأمر',
  success: 'تم تسجيل الدفعة',
  genericError: 'تعذر تسجيل الدفعة، حاول مرة أخرى',
  deleted: 'تم حذف الدفعة',
  deleteError: 'تعذر حذف الدفعة',
  deleteConfirmTitle: 'حذف الدفعة',
  deleteConfirmMsg:
    'سيتم حذف الدفعة وعكس أثرها تلقائيًا: تُخصم من الخزينة إن كانت نقدية، ويُعاد فتح الأمر إن كان مغلقًا. هل تريد المتابعة؟',
  // overpayment → credit
  overpayTitle: 'دفعة تتجاوز المتبقي',
  overpayConfirm: (excess: string, name: string) =>
    `المبلغ يتجاوز المتبقي على الأمر بمقدار ${excess}. سيتم سداد الأمر بالكامل، ويُضاف الفائض رصيدًا لحساب «${name}» يُستخدم في طلبات قادمة أو يُسترد لاحقًا. هل تريد المتابعة؟`,
  overpayProceed: 'سداد وإضافة رصيد',
  overpaid: (excess: string) => `تم السداد وإضافة ${excess} إلى رصيد العميل`,
  // apply stored credit to this order
  useCredit: 'استخدام رصيد العميل',
  useCreditTitle: 'استخدام رصيد العميل',
  creditAvailable: 'الرصيد المتاح',
  applyAmount: 'المبلغ المستخدم من الرصيد',
  applyProceed: 'خصم من الرصيد',
  applied: 'تم استخدام الرصيد في سداد الأمر',
  // vendor advance (عربون) — PO overpayment → advance, and applying it back
  overpayConfirmVendor: (excess: string, name: string) =>
    `المبلغ يتجاوز المتبقي على الأمر بمقدار ${excess}. سيتم سداد الأمر بالكامل، ويُسجَّل الفائض دفعةً مقدّمةً لدى «${name}» تُخصم من أوامر شراء قادمة أو تُسترد لاحقًا. هل تريد المتابعة؟`,
  overpaidVendor: (excess: string) => `تم السداد وتسجيل ${excess} كدفعة مقدّمة للمورّد`,
  useAdvance: 'خصم من الدفعة المقدّمة',
  advanceAvailable: 'الدفعة المقدّمة المتاحة',
  applyAmountVendor: 'المبلغ المخصوم من الدفعة المقدّمة',
  appliedVendor: 'تم خصم الدفعة المقدّمة من الأمر',
} as const;

export const VENDOR_CREDIT = {
  title: 'الدفعات المقدّمة للمورّد',
  subtitle: 'مبالغ مدفوعة مقدَّمًا للمورّد تُخصم من أوامر الشراء القادمة أو تُسترد',
  balance: 'إجمالي الدفعات المقدّمة',
  noMovements: 'لا توجد دفعات مقدّمة بعد',
  deposit: 'دفعة مقدّمة',
  depositTitle: 'دفعة مقدّمة للمورّد',
  refund: 'استرداد',
  refundTitle: 'استرداد دفعة مقدّمة',
  amount: 'المبلغ',
  method: 'الطريقة',
  drawerSite: 'من/إلى خزينة أي فرع؟',
  note: 'ملاحظة',
  by: 'بواسطة',
  depositDone: 'تم تسجيل الدفعة المقدّمة',
  refundDone: 'تم استرداد الدفعة المقدّمة',
  refundExceeds: 'المبلغ يتجاوز الرصيد المتاح',
  genericError: 'تعذر إتمام العملية، حاول مرة أخرى',
  // movement source labels
  source_overpayment: 'دفعة زائدة على أمر',
  source_deposit: 'دفعة مقدّمة',
  source_applied: 'خصم من أمر',
  source_refund: 'استرداد',
  source_adjustment: 'تسوية',
} as const;

export const CREDIT = {
  title: 'رصيد العميل',
  subtitle: 'مبالغ محفوظة للعميل تُستخدم في طلبات قادمة أو تُسترد',
  balance: 'الرصيد الحالي',
  noCredit: 'لا يوجد رصيد محفوظ',
  noMovements: 'لا توجد حركات رصيد بعد',
  deposit: 'إضافة رصيد',
  depositTitle: 'إضافة رصيد للعميل',
  refund: 'استرداد رصيد',
  refundTitle: 'استرداد رصيد للعميل',
  amount: 'المبلغ',
  method: 'الطريقة',
  drawerSite: 'من/إلى خزينة أي فرع؟',
  note: 'ملاحظة',
  by: 'بواسطة',
  depositDone: 'تمت إضافة الرصيد',
  refundDone: 'تم استرداد الرصيد',
  refundExceeds: 'المبلغ يتجاوز الرصيد المتاح',
  genericError: 'تعذر إتمام العملية، حاول مرة أخرى',
  // movement source labels
  source_overpayment: 'دفعة زائدة',
  source_deposit: 'إيداع رصيد',
  source_applied: 'استخدام في أمر',
  source_refund: 'استرداد',
  source_adjustment: 'تسوية',
} as const;

// ---------------------------------------------------------------------------
// الصلاحيات — one label per permission_keys row (migration 0031).
// Phrased as what the person may DO, not as a feature name, because an admin
// reading a list of thirty toggles is deciding about a person, not a module.
// ---------------------------------------------------------------------------
export const PERM_AREA: Record<string, string> = {
  sales: 'المبيعات',
  purchases: 'المشتريات',
  inventory: 'المخزون',
  payments: 'الدفعات',
  cash: 'الخزينة',
  contacts: 'جهات الاتصال',
  documents: 'المستندات',
  reports: 'التقارير',
  admin: 'الإدارة',
};

export const PERM_LABEL: Record<string, string> = {
  'sales.view': 'عرض أوامر البيع',
  'sales.draft': 'إنشاء وتعديل مسودات البيع',
  'sales.discount': 'عمل خصم على أمر البيع',
  'sales.invoice': 'فوترة أوامر البيع',
  'sales.place': 'تنفيذ الأمر وخصم المخزون',
  'sales.cancel_placement': 'إلغاء التنفيذ وإرجاع المخزون',
  'sales.edit_locked': 'تعديل أمر بيع بعد فوترته',
  'sales.delete': 'حذف أمر بيع',
  'purchases.view': 'عرض أوامر الشراء',
  'purchases.create': 'إنشاء أمر شراء',
  'purchases.edit': 'تعديل أمر شراء',
  'purchases.convert': 'التحويل إلى المخزون',
  'purchases.delete': 'حذف أمر شراء أو عكس تحويل',
  'inventory.view': 'عرض الأصناف والأرصدة',
  'inventory.items': 'إضافة وتعديل الأصناف والأسعار',
  'inventory.adjust': 'تسوية المخزون',
  'inventory.transfer': 'النقل بين الفروع',
  'inventory.item_delete': 'حذف صنف',
  'payments.record': 'تسجيل دفعة',
  'payments.credit': 'استخدام أو رد رصيد العميل/المورد',
  'payments.delete': 'حذف دفعة',
  'cash.view': 'عرض رصيد الخزينة وحركاتها',
  'cash.manual': 'إيداع / سحب / تسوية بالخزينة',
  'contacts.view': 'عرض جهات الاتصال وكشوف الحساب',
  'contacts.manage': 'إضافة وتعديل جهات الاتصال',
  'contacts.delete': 'حذف جهة اتصال',
  'attachments.manage': 'إرفاق وحذف مستندات الأوامر',
  'reports.view': 'فتح صفحة التقارير',
  'audit.view': 'قراءة سجل التدقيق',
  'users.manage': 'إدارة المستخدمين والصلاحيات',
  'sites.manage': 'إدارة الفروع',
  'settings.manage': 'تعديل بيانات المنشأة',
};

export const ACCESS = {
  title: 'الصلاحيات',
  preset: 'القالب',
  presetAdmin: 'مدير النظام',
  presetManager: 'مدير',
  presetStaff: 'موظف',
  presetCustom: 'مخصص',
  presetHint: 'اختيار قالب يملأ الصلاحيات كنقطة بداية — عدّل ما تشاء بعدها',
  copyFrom: 'نسخ الصلاحيات من مستخدم',
  copyFromPlaceholder: 'اختر مستخدمًا',
  copied: 'تم نسخ الصلاحيات — لم تُحفظ بعد',
  branches: 'الفروع',
  allBranches: 'كل الفروع',
  pickBranches: 'فروع محددة',
  branchesRequired: 'اختر فرعًا واحدًا على الأقل',
  adminAllAccess: 'مدير النظام لديه كل الصلاحيات على كل الفروع — لا يمكن تقييده',
  selfWarning: 'لا يمكنك تعديل دورك أو صلاحياتك بنفسك',
  selectAll: 'تحديد الكل',
  clearAll: 'إلغاء الكل',
  countSelected: 'صلاحية مفعّلة',
  saved: 'تم حفظ الصلاحيات',
  saveError: 'تعذر حفظ الصلاحيات',
  noPermission: 'غير مصرح لك بهذا الإجراء',
} as const;

export const USERS = {
  title: 'المستخدمون',
  subtitle: 'حسابات فريق العمل وأدوارهم وصلاحياتهم',
  colName: 'الاسم',
  colRole: 'الدور',
  colStatus: 'الحالة',
  colSince: 'منذ',
  active: 'نشط',
  inactive: 'موقوف',
  editUser: 'تعديل المستخدم',
  fullName: 'الاسم الكامل',
  role: 'الدور',
  activeLabel: 'الحساب نشط',
  nameRequired: 'الاسم مطلوب',
  saved: 'تم حفظ بيانات المستخدم',
  saveError: 'تعذر حفظ بيانات المستخدم',
  selfRoleWarning: 'لا يمكنك تغيير دورك أو إيقاف حسابك بنفسك',
  createNote:
    'يمكنك إنشاء حسابات فريق العمل من هنا مباشرة. الحساب الأول (المدير) فقط يُنشأ من لوحة تحكم Supabase.',
  noUsers: 'لا يوجد مستخدمون بعد',
  // Create-user modal
  addUser: 'إضافة مستخدم',
  createUser: 'إنشاء حساب جديد',
  colUsername: 'اسم الدخول',
  username: 'اسم المستخدم (للدخول)',
  usernamePlaceholder: 'مثال: ahmed',
  usernameHint: 'يستخدمه الموظف لتسجيل الدخول. حروف إنجليزية وأرقام فقط، بدون مسافات.',
  password: 'كلمة المرور المبدئية',
  passwordHint: 'يسلّمها المدير للموظف، ويمكنه تغييرها لاحقًا. 6 أحرف على الأقل.',
  usernameRequired: 'اسم المستخدم مطلوب',
  usernameInvalid: 'اسم المستخدم يقبل الحروف الإنجليزية والأرقام والنقطة والشرطة فقط',
  passwordRequired: 'كلمة المرور مطلوبة (6 أحرف على الأقل)',
  createdUser: 'تم إنشاء الحساب',
  createError: 'تعذر إنشاء الحساب',
  emailExists: 'اسم المستخدم مستخدم بالفعل',
  forbidden: 'هذه العملية متاحة للمدير فقط',
  create: 'إنشاء الحساب',
} as const;

export const SITES_ADMIN = {
  title: 'الإعدادات — الفروع',
  subtitle: 'إدارة فروع المنشأة',
  addSite: 'إضافة فرع',
  editSite: 'تعديل الفرع',
  colName: 'اسم الفرع',
  colStatus: 'الحالة',
  colDrawer: 'رصيد الخزينة',
  colSince: 'منذ',
  active: 'نشط',
  inactive: 'موقوف',
  name: 'اسم الفرع',
  namePlaceholder: 'مثال: فرع المنصورة',
  activeLabel: 'الفرع نشط',
  activeHint: 'الفرع الموقوف يختفي من القوائم لكن يبقى سجله محفوظًا',
  nameRequired: 'اسم الفرع مطلوب',
  savedNew: 'تمت إضافة الفرع',
  savedEdit: 'تم حفظ التعديلات',
  saveError: 'تعذر حفظ الفرع',
  noSites: 'لا توجد فروع بعد',
} as const;

export const AUDIT = {
  title: 'سجل النشاط',
  subtitle: 'من قام بأي إجراء ومتى — للمدير والمشرف',
  colWhen: 'التاريخ والوقت',
  colUser: 'المستخدم',
  colAction: 'الإجراء',
  colDetails: 'التفاصيل',
  system: 'النظام',
  unknownUser: 'مستخدم محذوف',
  allEntities: 'كل الأنواع',
  allActions: 'كل الإجراءات',
  from: 'من',
  to: 'إلى',
  noEvents: 'لا يوجد نشاط في هذه الفترة',
  print: 'طباعة',
} as const;

// Action verb per (entity, action) — keeps the trail readable in Arabic.
export const AUDIT_ACTION_LABEL: Record<string, string> = {
  insert: 'إضافة',
  update: 'تعديل',
  delete: 'حذف',
};

export const AUDIT_ENTITY_LABEL: Record<string, string> = {
  payments: 'دفعة',
  sales_orders: 'أمر بيع',
  purchase_orders: 'أمر شراء',
  po_conversions: 'تحويل مشتريات',
  stock_transfers: 'نقل مخزون',
  stock_movements: 'تسوية مخزون',
  cash_movements: 'حركة خزينة',
  client_credits: 'رصيد عميل',
  items: 'صنف',
  contacts: 'جهة اتصال',
  profiles: 'مستخدم',
  sites: 'فرع',
  organization: 'بيانات النشاط',
};

export const ORG_SETTINGS = {
  sectionTitle: 'بيانات النشاط',
  sectionHint: 'يظهر هذا الاسم والعنوان في الفواتير وكشوف الحساب وأعلى القائمة الجانبية.',
  businessName: 'اسم النشاط',
  businessNamePlaceholder: 'مثال: شبانة لتجارة الألوميتال',
  addressLine: 'العنوان',
  addressPlaceholder: 'المدينة، الشارع، رقم المبنى',
  phoneLine: 'الهاتف',
  phonePlaceholder: 'هاتف: 057-0000000',
  currency: 'العملة',
  currencyHint: 'تظهر مع كل المبالغ في الفواتير وكشوف الحساب',
  timezone: 'المنطقة الزمنية',
  timezoneHint: 'تحدد بداية ونهاية اليوم في لوحة التحكم والخزينة',
  nameRequired: 'اسم النشاط مطلوب',
  saved: 'تم حفظ بيانات النشاط',
  saveError: 'تعذر حفظ بيانات النشاط',
  save: 'حفظ بيانات النشاط',
} as const;

export const REPORTS = {
  title: 'التقارير',
  subtitle: 'تقارير المبيعات والمشتريات وحركة الخزينة والأرصدة',
  from: 'من',
  to: 'إلى',
  print: 'طباعة',
  tabSales: 'المبيعات',
  tabPurchases: 'المشتريات',
  tabCash: 'حركة الخزينة',
  tabBalances: 'الأرصدة',
  // sales / purchases tables
  colDoc: 'المستند',
  colParty: 'الطرف',
  colDate: 'التاريخ',
  colTotal: 'الإجمالي',
  colPaid: 'المدفوع',
  colRemaining: 'المتبقي',
  colStatus: 'الحالة',
  ordersCount: 'عدد الأوامر',
  totalsTag: 'الإجمالي',
  paidTag: 'المحصل',
  remainingTag: 'المتبقي',
  noRows: 'لا توجد بيانات في هذه الفترة',
  // cash tab
  cashSite: 'الخزينة',
  allSitesCash: 'كل الخزائن',
  colReason: 'البيان',
  colAmount: 'المبلغ',
  colBalanceAfter: 'الرصيد بعد',
  inflowTag: 'وارد',
  outflowTag: 'صادر',
  closingTag: 'رصيد آخر الفترة',
  manualMovement: 'حركة يدوية',
  manualDeposit: 'إيداع',
  manualWithdraw: 'سحب',
  manualAdjust: 'تسوية',
  manualType: 'نوع الحركة',
  manualAmount: 'المبلغ',
  manualAmountHint: 'في التسوية: قيمة موجبة تزيد الخزينة وسالبة تخصم منها',
  manualReason: 'السبب / البيان',
  manualReasonPlaceholder: 'اكتب سبب الحركة...',
  manualReasonRequired: 'سبب الحركة مطلوب',
  manualAmountRequired: 'أدخل مبلغًا غير صفري',
  manualSiteLabel: 'الفرع (الخزينة)',
  manualSuccess: 'تم تسجيل الحركة اليدوية',
  manualError: 'تعذر تسجيل الحركة',
  // balances tab
  colContact: 'جهة الاتصال',
  colType: 'النوع',
  colBalance: 'الرصيد',
  owedToUs: 'إجمالي المستحق لنا (عليهم)',
  owedByUs: 'إجمالي المستحق علينا (لهم)',
  noBalances: 'كل الحسابات متسوية',
} as const;

/** لوحة المشغّل — creating and listing CLIENT BUSINESSES. Operator-only;
 *  never shown to a tenant admin, however senior. */
export const PLATFORM = {
  title: 'المنشآت',
  subtitle: 'إدارة منشآت العملاء',
  create: 'منشأة جديدة',
  createTitle: 'إنشاء منشأة جديدة',
  slug: 'كود المنشأة (بالإنجليزية)',
  slugHint: 'يُستخدم في رابط الدخول واسم حساب المستخدم — لا يمكن تغييره لاحقاً',
  businessName: 'اسم المنشأة',
  ownerName: 'اسم المدير',
  ownerUsername: 'اسم مستخدم المدير',
  ownerPassword: 'كلمة مرور المدير',
  siteName: 'اسم الفرع الرئيسي',
  addressLine: 'العنوان',
  phoneLine: 'الهاتف',
  colSlug: 'الكود',
  colName: 'المنشأة',
  colUsers: 'المستخدمون',
  colSites: 'الفروع',
  colCreated: 'أُنشئت',
  colStatus: 'الحالة',
  active: 'نشطة',
  inactive: 'موقوفة',
  loginLink: 'رابط الدخول',
  created: 'تم إنشاء المنشأة',
  noOrgs: 'لا توجد منشآت بعد',
  forbidden: 'هذه الصفحة مخصّصة لمشغّل النظام فقط',
  invalidSlug: 'الكود يجب أن يكون حروفاً إنجليزية صغيرة وأرقاماً وشرطات فقط',
  slugExists: 'هذا الكود مستخدم بالفعل',
  genericError: 'تعذّر إنشاء المنشأة',
} as const;
